### ISSUE TITLE
Allow postCreate, postUpdate, postDelete middleware to access the affected document

### ISSUE THREAD

**Issue by sgilroy** [florianholzapfel/express-restify-mongoose#236]
The postCreate, postUpdate, and postDelete middleware can access the output via `req.erm.result` but the Mongoose document (prior to being stripped down to a plain object via `item.toObject()` in `resource_filter.js`) is not available. My application needs access to the document for some additional processing.

This can be implemented by simply setting `req.erm.document = item;` in each of the appropriate operations. I have a working implementation which I can submit as a pull request.

**Comment by Zertz** [comment]
Great minds think alike! Can you try the master branch?

Filtering now happens right before output so all post middleware should now have access to the entire document.

**Comment by sgilroy** [comment]
Should the full document be available via `req.erm.document` or `req.erm.result` or something else?

For reference, this issue appears to be a duplicate of #186 and resolved by #217.

I have not tested the version from master yet. Will there be a release soon with this enhancement?

Attempting to npm install from master or the specific commit did not work for me.
```
npm install git+https://github.com/florianholzapfel/express-restify-mongoose.git --save
npm install git://github.com/florianholzapfel/express-restify-mongoose.git#4f40b54e338718c243d438fbb00722a94fe7de11 --save
```

How do you recommend I get the master branch?

**Comment by Zertz** [comment]
The full document is available on `req.erm.result` as before. Keep in mind that if you use `lean: true` this will be a simple object and not a mongoose document.

`npm i florianholzapfel/express-restify-mongoose`

**Comment by joshcartme** [comment]
Sorry if I'm missing something, should this work in 2.4.2 from npm?

I have code like this:
```
restify.serve(router, User, {
  lean: false,
  postCreate: function(req, res, next) {
    var password = req.body.password;
    delete req.body.password;

    req.erm.result.setPassword(password, function(passErr) {
      if (passErr) {
        next(passErr);
      } else {
        next(err);
      }
    });
  },
  preUpdate: function(req, res, next) {
    var user = req.erm.document,
        password = req.body.password;
    delete req.body.password;
    if (password) {
      user.setPassword(password, next);
    } else {
      next();
    }
  }
});
```
`setPassword` is an instance method added by passport-local-mongoose.

`postCreate` always fails with:
```
TypeError: req.erm.result.setPassword is not a function
```

Where as `preUpdate` has no issue, the difference being that `postCreate` uses `req.erm.result` while `preUpdate` uses `req.erm.document`

**Comment by Zertz** [comment]
You are correct, this does not work in the latest published version. It will be in the next release.

**Comment by joshcartme** [comment]
@Zertz thanks, sorry for the noise!

**Comment by Zertz** [comment]
@sgilroy @joshcartme 

3.0.0 is on npm, please read the [changelog](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/CHANGELOG.md) before upgrading.
